<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: tikenix
 * Date: Fri, 25 Sep 2020 03:16:12 +0000
 */

$conf['title'] = 'wiki.tikenix';
$conf['lang'] = 'fr';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'kennymarechal@gmail.com';
$conf['proxy']['pass'] = '<b>dG9hZDc4MTIyNw==';
