# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 25 Sep 2020 01:02:34 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

tikenix:$2y$10$fGUxXmb7n2fvxCBpXASCfuQ0BH8ydcq7kMcHqrKn3HHJU2vDfYjfu:kenny:kennymarechal@gmail.com:admin,user
